Twitch = "True" #twitch or bilibili
BiliBili = "False" #twitch or bilibili
Chrome_Profile = "" #chrome profile folder name
username = "" #twitch or bilibili username
ytshort = "False" #not recommand
unliststream = "False" #after stream will be public
disablechat = "True"  #disable chat on live stream
accountname = "" #google account name(not brand acc have email) when login to google api
brandacc = "False" #do you use the brand acc as the archive channel
brandaccname = "Null" #if you have brand acc copy the google account name when login to google api
ffmpeg1 = "ffmpeg111.exe" #ffmpeg exe name
ffmpeg = "ffmpeg.exe" #ffmpeg exe name
apiexe = "ffmpeg_api.exe" #api exe name
rtmpkeyname1 = "1" + "username" + "mult" #first yt rtmp key name
rtmpkeyname = "username" #second yt rtmp key name
rtmp_key = "" #first yt rtmp key
rtmp_key_1 = "" #second yt rtmp key
client_id = "" #twitch api client id
client_secret = "" #twitch api client sercet
